---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
helmCharts:
  - name: keycloakx
    repo: https://codecentric.github.io/helm-charts
    releaseName: keycloak
    version: 7.1.1
    valuesFile: values.yaml
    namespace: auth
