---
repos:
  # yaml formatting
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
        args:
          - "-conf=yamlfmt.yaml"

  # secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
        args:
          - "--config=gitleaks.toml"
